Дз2
js-tasks-ru/jsbasic-20220811_grevold pull request #3
Opened 2022-08-24 13:31 UTC by grevold

2022-08-24 13:32 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-08-25 05:41 UTC, koalex requested changes
Исправить замечание **2-3**

2022-08-25 05:41 UTC, koalex commented on 2-module/3-task/index.js
> +    calculator.a = a;
```
this.a = a;
this.b = b;
```

2022-08-25 10:02 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-08-26 08:06 UTC, koalex approved these changes

2022-08-26 08:06 UTC, merged